# Generated by Django 2.0.2 on 2018-04-12 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.TextField()),
                ('bike_type', models.CharField(choices=[('RD', 'Road Bike'), ('CB', 'Cruiser Bike'), ('MT', 'Mountain Bike')], default='CB', max_length=2)),
                ('vin', models.IntegerField(blank=True, null=True)),
                ('state', models.CharField(choices=[('GT', 'Green Tag'), ('WT', 'White Tag'), ('BT', 'Black Tag')], default='WT', max_length=2)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
