# Generated by Django 2.1.2 on 2018-12-11 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import localflavor.us.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('make', models.TextField()),
                ('model', models.TextField()),
                ('vin', models.IntegerField(blank=True, null=True)),
                ('color_id', models.CharField(choices=[('RD', 'Road'), ('MT', 'Mountain'), ('H', 'Hybrid'), ('CB', 'Cruiser'), ('RT', 'Recumbent'), ('TM', 'Tandem'), ('F', 'Folding'), ('TR', 'Trike'), ('UN', 'Unicycle'), ('K', 'Kids')], default=None, max_length=2, null=True)),
                ('biketype_id', models.CharField(choices=[('RD', 'Road'), ('MT', 'Mountain'), ('H', 'Hybrid'), ('CB', 'Cruiser'), ('RT', 'Recumbent'), ('TM', 'Tandem'), ('F', 'Folding'), ('TR', 'Trike'), ('UN', 'Unicycle'), ('K', 'Kids')], default=None, max_length=2, null=True)),
                ('size', models.CharField(blank=True, max_length=6)),
                ('speeds', models.IntegerField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('disposal_date', models.DateField(blank=True)),
                ('state_id', models.CharField(choices=[('G', 'Green Tag'), ('B', 'Blue Tag'), ('Y', 'Yellow Tag'), ('W', 'White Tag'), ('O', 'Orange Tag'), ('R', 'Red Tag')], default='WT', max_length=2)),
                ('value', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address_1', models.CharField(max_length=128, verbose_name='address')),
                ('address_2', models.CharField(blank=True, max_length=128, verbose_name="address cont'd")),
                ('city', models.CharField(default='Corvallis', max_length=64, verbose_name='city')),
                ('state', localflavor.us.models.USStateField(default='OR', max_length=2, verbose_name='state')),
                ('zip_code', localflavor.us.models.USZipCodeField(default='97330', max_length=10, verbose_name='zip code')),
                ('whyhere_id', models.IntegerField(choices=[(0, 'Work on own bike'), (1, 'Work on friends bike'), (2, 'Buy bike'), (3, 'Get parts'), (4, 'Volunteer'), (5, 'Other')], default=None, null=True)),
                ('foundhow_id', models.IntegerField(choices=[(0, 'Internet'), (1, 'FaceBook'), (2, 'Friend'), (3, 'Event'), (4, 'Flyer'), (5, 'Random'), (6, 'Other')], default=None, null=True)),
                ('volunteer_hrs', models.IntegerField(default=0)),
                ('bench_hrs', models.IntegerField(default=0)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('gender_id', models.IntegerField(choices=[(1, 'Female'), (2, 'Male'), (3, 'TransMale'), (4, 'TransFemale'), (5, 'Gender NonConforming'), (6, 'Something Else'), (7, 'Decline to Answer')], default=None, null=True)),
                ('pronoun_id', models.IntegerField(choices=[(1, 'He'), (2, 'She'), (3, 'They'), (4, 'Ze'), (5, 'N/A'), (6, 'No Preference')], default=None, null=True)),
                ('role_id', models.PositiveSmallIntegerField(blank=True, choices=[(4, 'Admin'), (3, 'Manager'), (2, 'Volunteer'), (1, 'User'), (0, 'No Waiver')], null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('sale_time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('salestype_id', models.IntegerField(choices=[('CM', 'Cash Money'), ('CC', 'Credit Card'), ('PP', 'PayPal')], default='CM')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('details', models.TextField(null=True)),
                ('notes', models.TextField(null=True)),
                ('bike_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.Bike')),
                ('buyer_people_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer_sale_set', to='bikes.People')),
                ('manager_people_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_sale_set', to='bikes.People')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftLog',
            fields=[
                ('in_time', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('out_time', models.DateTimeField()),
                ('in_cash', models.DecimalField(decimal_places=2, max_digits=6)),
                ('out_cash', models.DecimalField(blank=True, decimal_places=2, max_digits=6)),
                ('in_memo', models.TextField(blank=True, null=True)),
                ('out_memo', models.TextField(blank=True, null=True)),
                ('open_manager_people_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closeman_shiftlog_set', to='bikes.People')),
            ],
        ),
        migrations.CreateModel(
            name='UseLog',
            fields=[
                ('in_time', models.DateTimeField(auto_now=True, primary_key=True, serialize=False)),
                ('out_time', models.DateTimeField()),
                ('volunteering', models.BooleanField(default=False)),
                ('bench', models.IntegerField(blank=True, null=True)),
                ('user_people_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bikes.People')),
            ],
        ),
        migrations.AddField(
            model_name='bike',
            name='donor_people_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donor_bike_set', to='bikes.People'),
        ),
        migrations.AddField(
            model_name='bike',
            name='manager_people_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manager_bike_set', to='bikes.People'),
        ),
        migrations.AddField(
            model_name='bike',
            name='owner_people_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_bike_set', to='bikes.People'),
        ),
    ]
